apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbveileder
  namespace: {{namespace}}
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbveileder/veilarbveileder:{{version}}
  port: 8080
  secureLogs:
    enabled: true
  liveness:
    path: veilarbveileder/internal/isAlive
    initialDelay: 15
  readiness:
    path: veilarbveileder/internal/selftest
    initialDelay: 15
  prometheus:
    enabled: true
    path: veilarbveileder/internal/metrics
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - https://veilarbveileder-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/veilarbveileder
  vault:
    enabled: true
  envFrom:
    - configmap: pto-config
  env:
    - name: LDAP_BASEDN
      value: dc=preprod,dc=local
    - name: LDAP_USER_BASEDN
      value: ou=NAV,ou=BusinessUnits,dc=preprod,dc=local
    - name: LDAP_SERVICEUSER_BASEDN
      value: ou=ServiceAccounts,dc=preprod,dc=local
    - name: LDAP_URL
      value: ldaps://ldapgw.preprod.local
    - name: LDAP_DOMAIN
      value: PREPROD.LOCAL
